### ISSUE TITLE
Scope of option chain

### ISSUE THREAD

**Issue by shvjds** [vetalas/options-app_plan#5]
Amend [Options-app plan](https://github.com/vetalas/options-app_plan/blob/master/options-app_plan.md) to whether we will include only index options or also stock option info

**Comment by gitnj** [comment]
I think we should go in this order:

# Stage 1
Weekly and monthly expiring of
* NIFTY
* BANKNIFTY

# Stage 2
NIFTY50 stock options.

# Stage 3
Stocks outside this the above two.

@shvjds If this sounds good, I'll go ahead and add it.

**Comment by shvjds** [comment]
Looks good. Add it
